# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5678dd5a2898dd03b9eddbd2fc846385d66fb4246a762d7977a353bedaf07c2e90858128d160dbfcb25b3c22dc66c1e813cc0d904f56421e93e74b56050c151d

test:
  secret_key_base: 6264989b3ee835a7294559db66c3bc49ecd71038f41aea8ff4d435c8cf2e0a3abbe9b2419f1cb42d027864a26b72e90d4b87af11948734a0cd87da127428cd50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
